name: npm-publish-prod

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-beta.*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: 🔨安装依赖
        run: pnpm i
      - name: 🎁包发布
        run: pnpm -r publish --no-git-checks --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
